#pragma once

#include "sdkconfig.h"

//--------------------------------------------------------------------------------------------------
// Camera Config

#define EP_CAM_XCLK_FREQ_HZ CONFIG_EP_CAM_XCLK_FREQ_HZ

#if CONFIG_EP_CAM_LEDC_TIMER_0
#define EP_CAM_LEDC_TIMER (LEDC_TIMER_0)
#elif CONFIG_EP_CAM_LEDC_TIMER_1
#define EP_CAM_LEDC_TIMER (LEDC_TIMER_1)
#elif CONFIG_EP_CAM_LEDC_TIMER_2
#define EP_CAM_LEDC_TIMER (LEDC_TIMER_2)
#elif CNOFIG_EP_CAM_LEDC_TIMER_3
#define EP_CAM_LEDC_TIMER (LEDC_TIMER_3)
#else
#define EP_CAM_LEDC_TIMER (LEDC_TIMER_0)
#endif

#if CONFIG_EP_CAM_LEDC_CHANNEL_0
#define EP_CAM_LEDC_CHANNEL (LEDC_CHANNEL_0)
#elif CONFIG_EP_CAM_LEDC_CHANNEL_1
#define EP_CAM_LEDC_CHANNEL (LEDC_CHANNEL_1)
#elif CONFIG_EP_CAM_LEDC_CHANNEL_2
#define EP_CAM_LEDC_CHANNEL (LEDC_CHANNEL_2)
#elif CNOFIG_EP_CAM_LEDC_CHANNEL_3
#define EP_CAM_LEDC_CHANNEL (LEDC_CHANNEL_3)
#elif CNOFIG_EP_CAM_LEDC_CHANNEL_4
#define EP_CAM_LEDC_CHANNEL (LEDC_CHANNEL_4)
#elif CNOFIG_EP_CAM_LEDC_CHANNEL_5
#define EP_CAM_LEDC_CHANNEL (LEDC_CHANNEL_5)
#else
#define EP_CAM_LEDC_CHANNEL (LEDC_CHANNEL_0)
#endif

#if CONFIG_EP_CAM_MODULE_WROVER_KIT // Wrover Kit
#define EP_CAM_MODULE_NAME ("Wrover Kit")
#define EP_CAM_PIN_PWDN (-1)
#define EP_CAM_PIN_RESET (-1)
#define EP_CAM_PIN_XCLK (21)
#define EP_CAM_PIN_SIOD (26)
#define EP_CAM_PIN_SIOC (27)
#define EP_CAM_PIN_D7 (35)
#define EP_CAM_PIN_D6 (34)
#define EP_CAM_PIN_D5 (39)
#define EP_CAM_PIN_D4 (36)
#define EP_CAM_PIN_D3 (19)
#define EP_CAM_PIN_D2 (18)
#define EP_CAM_PIN_D1 (5)
#define EP_CAM_PIN_D0 (4)
#define EP_CAM_PIN_VSYNC (25)
#define EP_CAM_PIN_HREF (23)
#define EP_CAM_PIN_PCLK (22)
#elif CONFIG_EP_CAM_MODULE_ESP_EYE // ESP-EYE
#define EP_CAM_MODULE_NAME ("ESP-EYE")
#define EP_CAM_PIN_PWDN (-1)
#define EP_CAM_PIN_RESET (-1)
#define EP_CAM_PIN_XCLK (4)
#define EP_CAM_PIN_SIOD (18)
#define EP_CAM_PIN_SIOC (23)
#define EP_CAM_PIN_D7 (36)
#define EP_CAM_PIN_D6 (37)
#define EP_CAM_PIN_D5 (38)
#define EP_CAM_PIN_D4 (39)
#define EP_CAM_PIN_D3 (35)
#define EP_CAM_PIN_D2 (14)
#define EP_CAM_PIN_D1 (13)
#define EP_CAM_PIN_D0 (34)
#define EP_CAM_PIN_VSYNC (5)
#define EP_CAM_PIN_HREF (27)
#define EP_CAM_PIN_PCLK (25)
#elif CONFIG_EP_CAM_MODULE_ESP_S2_KALUGA // ESP-S2-KALUGA
#define EP_CAM_MODULE_NAME ("ESP-S2-KALUGA")
#define EP_CAM_PIN_PWDN (-1)
#define EP_CAM_PIN_RESET (-1)
#define EP_CAM_PIN_XCLK (1)
#define EP_CAM_PIN_SIOD (8)
#define EP_CAM_PIN_SIOC (7)
#define EP_CAM_PIN_D7 (38)
#define EP_CAM_PIN_D6 (21)
#define EP_CAM_PIN_D5 (40)
#define EP_CAM_PIN_D4 (39)
#define EP_CAM_PIN_D3 (42)
#define EP_CAM_PIN_D2 (41)
#define EP_CAM_PIN_D1 (37)
#define EP_CAM_PIN_D0 (36)
#define EP_CAM_PIN_VSYNC (2)
#define EP_CAM_PIN_HREF (3)
#define EP_CAM_PIN_PCLK (33)
#elif CONFIG_EP_CAM_MODULE_ESP_S3_EYE // ESP-S3-EYE
#define EP_CAM_MODULE_NAME ("ESP-S3-EYE")
#define EP_CAM_PIN_PWDN (-1)
#define EP_CAM_PIN_RESET (-1)
#define EP_CAM_PIN_VSYNC (6)
#define EP_CAM_PIN_HREF (7)
#define EP_CAM_PIN_PCLK (13)
#define EP_CAM_PIN_XCLK (15)
#define EP_CAM_PIN_SIOD (4)
#define EP_CAM_PIN_SIOC (5)
#define EP_CAM_PIN_D0 (11)
#define EP_CAM_PIN_D1 (9)
#define EP_CAM_PIN_D2 (8)
#define EP_CAM_PIN_D3 (10)
#define EP_CAM_PIN_D4 (12)
#define EP_CAM_PIN_D5 (18)
#define EP_CAM_PIN_D6 (17)
#define EP_CAM_PIN_D7 (16)
#elif CONFIG_EP_CAM_MODULE_ESP32_CAM_BOARD // ESP-DEVCAM
#define EP_CAM_MODULE_NAME ("ESP-DEVCAM")
#define EP_CAM_PIN_PWDN (32)
#define EP_CAM_PIN_RESET (33)
#define EP_CAM_PIN_XCLK (4)
#define EP_CAM_PIN_SIOD (18)
#define EP_CAM_PIN_SIOC (23)
#define EP_CAM_PIN_D7 (36)
#define EP_CAM_PIN_D6 (19)
#define EP_CAM_PIN_D5 (21)
#define EP_CAM_PIN_D4 (39)
#define EP_CAM_PIN_D3 (35)
#define EP_CAM_PIN_D2 (14)
#define EP_CAM_PIN_D1 (13)
#define EP_CAM_PIN_D0 (34)
#define EP_CAM_PIN_VSYNC (5)
#define EP_CAM_PIN_HREF (27)
#define EP_CAM_PIN_PCLK (25)
#elif CONFIG_EP_CAM_MODULE_M5STACK_PSRAM // M5STACK-PSRAM
#define EP_CAM_MODULE_NAME ("M5STACK-PSRAM")
#define EP_CAM_PIN_PWDN (-1)
#define EP_CAM_PIN_RESET (15)
#define EP_CAM_PIN_XCLK (27)
#define EP_CAM_PIN_SIOD (25)
#define EP_CAM_PIN_SIOC (23)
#define EP_CAM_PIN_D7 (19)
#define EP_CAM_PIN_D6 (36)
#define EP_CAM_PIN_D5 (18)
#define EP_CAM_PIN_D4 (39)
#define EP_CAM_PIN_D3 (5)
#define EP_CAM_PIN_D2 (34)
#define EP_CAM_PIN_D1 (35)
#define EP_CAM_PIN_D0 (32)
#define EP_CAM_PIN_VSYNC (22)
#define EP_CAM_PIN_HREF (26)
#define EP_CAM_PIN_PCLK (21)
#elif CONFIG_EP_CAM_MODULE_M5STACK_WIDE // M5STACK-WIDE
#define EP_CAM_MODULE_NAME ("M5STACK-WIDE")
#define EP_CAM_PIN_PWDN (-1)
#define EP_CAM_PIN_RESET (15)
#define EP_CAM_PIN_XCLK (27)
#define EP_CAM_PIN_SIOD (22)
#define EP_CAM_PIN_SIOC (23)
#define EP_CAM_PIN_D7 (19)
#define EP_CAM_PIN_D6 (36)
#define EP_CAM_PIN_D5 (18)
#define EP_CAM_PIN_D4 (39)
#define EP_CAM_PIN_D3 (5)
#define EP_CAM_PIN_D2 (34)
#define EP_CAM_PIN_D1 (35)
#define EP_CAM_PIN_D0 (32)
#define EP_CAM_PIN_VSYNC (25)
#define EP_CAM_PIN_HREF (26)
#define EP_CAM_PIN_PCLK (21)
#elif CONFIG_EP_CAM_MODULE_AI_THINKER // AI-THINKER
#define EP_CAM_MODULE_NAME ("AI-THINKER")
#define EP_CAM_PIN_PWDN (32)
#define EP_CAM_PIN_RESET (-1)
#define EP_CAM_PIN_XCLK (0)
#define EP_CAM_PIN_SIOD (26)
#define EP_CAM_PIN_SIOC (27)
#define EP_CAM_PIN_D7 (35)
#define EP_CAM_PIN_D6 (34)
#define EP_CAM_PIN_D5 (39)
#define EP_CAM_PIN_D4 (36)
#define EP_CAM_PIN_D3 (21)
#define EP_CAM_PIN_D2 (19)
#define EP_CAM_PIN_D1 (18)
#define EP_CAM_PIN_D0 (5)
#define EP_CAM_PIN_VSYNC (25)
#define EP_CAM_PIN_HREF (23)
#define EP_CAM_PIN_PCLK (22)
#elif CONFIG_EP_CAM_MODULE_CUSTOM // CUSTOM
#define EP_CAM_MODULE_NAME ("CUSTOM")
#define EP_CAM_PIN_PWDN (CONFIG_EP_CAM_PIN_PWDN)
#define EP_CAM_PIN_RESET (CONFIG_EP_CAM_PIN_RESET)
#define EP_CAM_PIN_XCLK (CONFIG_EP_CAM_PIN_XCLK)
#define EP_CAM_PIN_SIOD (CONFIG_EP_CAM_PIN_SIOD)
#define EP_CAM_PIN_SIOC (CONFIG_EP_CAM_PIN_SIOC)
#define EP_CAM_PIN_D7 (CONFIG_EP_CAM_PIN_D7)
#define EP_CAM_PIN_D6 (CONFIG_EP_CAM_PIN_D6)
#define EP_CAM_PIN_D5 (CONFIG_EP_CAM_PIN_D5)
#define EP_CAM_PIN_D4 (CONFIG_EP_CAM_PIN_D4)
#define EP_CAM_PIN_D3 (CONFIG_EP_CAM_PIN_D3)
#define EP_CAM_PIN_D2 (CONFIG_EP_CAM_PIN_D2)
#define EP_CAM_PIN_D1 (CONFIG_EP_CAM_PIN_D1)
#define EP_CAM_PIN_D0 (CONFIG_EP_CAM_PIN_D0)
#define EP_CAM_PIN_VSYNC (CONFIG_EP_CAM_PIN_VSYNC)
#define EP_CAM_PIN_HREF (CONFIG_EP_CAM_PIN_HREF)
#define EP_CAM_PIN_PCLK (CONFIG_EP_CAM_PIN_PCLK)
#endif

//--------------------------------------------------------------------------------------------------